server.port=8081
spring.application.name=fleet-track-backend

# OSRM Configuration
osrm.url=http://router.project-osrm.org

# Vehicle Simulation Configuration
vehicle.simulation.enabled=true
vehicle.simulation.interval=5000
